apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql
  template:
    metadata:
      labels:
        name: mysql
    spec:
      containers:
        - name: mysql
          image: afreydev/companies-db:latest
          imagePullPolicy: Never
          ports:
            - name: mysql
              containerPort: 3306
          env:
          - name: MYSQL_HOST
            value: mysql
          - name: MYSQL_ROOT_PASSWORD
            value: password
          - name: MYSQL_USER
            value: companies
          - name: MYSQL_DATABASE
            value: companies
          - name: MYSQL_PASSWORD
            value: password
