apiVersion: v1
kind: Service
metadata:
  name: api-canary
  labels:
    name: api-canary
spec:
  type: NodePort
  ports:
    - port: 5001
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    name: api
    env: canary